# Generated by Django 4.2.5 on 2023-09-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_detalleejercicio_ejercicio_plansemanal_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
